TabletopSimWeb/TabletopSimWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('chat/', include('chat.urls')),
    path('games/', include('tabletops.urls')),
    path('admin/', admin.site.urls),
]

TabletopSimWeb/chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

TabletopSimWeb/tabletops/urls.py
from django.urls import path

from . import views

app_name = 'tabletops'
urlpatterns = [
    path('', views.index, name='index'),
    path('templateadmin/', views.template_admin, name='template_admin'),
    path('template/<str:template_name>/', views.template_edit, name='template_edit'),
    path('createTemplate/', views.create, name='create'),
    path('newRoom/', views.create_room, name='newroom'),
    path('room/<str:room_name>/', views.room, name='room'),
    path('savetemp/', views.save_template, name='save_temp'),
    path('whitelist/', views.whitelist, name='whitelist'),
    path('history/', views.history, name='history'),
]

TabletopSimWeb/chat/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

#need to make peer to peer chat that can be deleted if either user is if security is necessary

class ChatRoom(models.Model):
    name = models.CharField(max_length=200, primary_key=True)
    public = models.BooleanField(default=False)
    admin = models.ForeignKey(User, on_delete=models.CASCADE, related_name='adminrooms')
    whitelist = models.ManyToManyField(User, related_name='chatrooms')

    def __str__(self):
        return self.name + ' - ' + self.admin.username

class Message(models.Model):
    room = models.ForeignKey(ChatRoom, on_delete=models.CASCADE, related_name='messages')
    username = models.CharField(max_length=200)
    time = models.DateTimeField(default=timezone.now)
    content = models.TextField()

    def __str__(self):
        return self.username + ' - ' + self.time.strftime('%d %b %X')

TabletopSimWeb/chat/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'chat/index.html', {})

def room(request, room_name):
    return render(request, 'chat/room.html', {
        'room_name': room_name
    })

TabletopSimWeb/chat/templates/chat/index.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br/>
    <input id="room-name-input" type="text" size="100"/><br/>
    <input id="room-name-submit" type="button" value="Enter"/>

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
</body>
</html>

TabletopSimWeb/chat/templates/chat/room-wip.html
<!DOCTYPE html>
<html>
  <head>
      <meta charset="utf-8"/>
      <title>Chat Room</title>
      <style type="text/css">
        textarea:disabled{
          color: inherit;
          background-color: darkgrey;
        }
      </style>
      <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
      <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  </head>
  <body>
    <div id='app'>
      <textarea id="chat-log" cols="100" rows="20" disabled>[[chatlog]]</textarea><br/>
      <input id="chat-message-input" type="text" size="100"/><br/>
      <input id="chat-message-submit" type="button" value="Send"/>
    </div>
  </body>
  <script>
  let app = new Vue({
    el: '#app',
    delimiters: ['[[',']]'],
    data: {
      roomName = "{{ room_name|escapejs }}",
      chatlog = '',
    },
    methods: {

    },
    created: function() {

      axios({
        method: 'get',
        url: '{% url 'chat:history' %}',
        headers: {
          'X-CSRFToken': '{{csrf_token}}'
        },
        params: {
          room: "{{ room_name|escapejs }}"
        }
      }).then((response) => {
        let resp = JSON.parse(response.data)
        console.log(resp)
        if (resp) {
          for message in resp
            this.chatlog += message.
        }
      })

      var chatSocket = new WebSocket(
          'ws://' + window.location.host + '/ws/chat/' + this.roomName + '/');

      chatSocket.onmessage = function(e) {
          var data = JSON.parse(e.data);
          var message = data['message'];
          document.querySelector('#chat-log').value += (message + '\n');
      };

      chatSocket.onclose = function(e) {
          console.error('Chat socket closed unexpectedly');
      };

      document.querySelector('#chat-message-input').focus();
      document.querySelector('#chat-message-input').onkeyup = function(e) {
          if (e.keyCode === 13) {  // enter, return
              document.querySelector('#chat-message-submit').click();
          }
      };

      document.querySelector('#chat-message-submit').onclick = function(e) {
          var messageInputDom = document.querySelector('#chat-message-input');
          var message = messageInputDom.value;
          chatSocket.send(JSON.stringify({
              'message': message
          }));

          messageInputDom.value = '';
      };
    }
  })
  </script>
</html>

TabletopSimWeb/chat/templates/chat/room.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
    <textarea id="chat-log" cols="100" rows="20"></textarea><br/>
    <input id="chat-message-input" type="text" size="100"/><br/>
    <input id="chat-message-submit" type="button" value="Send"/>
</body>
<script>
    var roomName = "{{ room_name|escapejs }}";

    var chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/chat/' + roomName + '/')

    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data)
        var message = data['message']
        var user = data['user']
        document.querySelector('#chat-log').value += (user + ': ' + message + '\n')
    }

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly')
    }

    document.querySelector('#chat-message-input').focus()
    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click()
        }
    }

    document.querySelector('#chat-message-submit').onclick = function(e) {
        var messageInputDom = document.querySelector('#chat-message-input')
        var message = messageInputDom.value
        chatSocket.send(JSON.stringify({
            'message': message
        }));

        messageInputDom.value = ''
    }
</script>
</html>