TabletopSimWeb/TabletopSimWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('chat/', include('chat.urls')),
    path('games/', include('tabletops.urls')),
    path('admin/', admin.site.urls),
]

TabletopSimWeb/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('home/', views.user_home, name='home'),
    path('login/', views.login_page, name='login'),
    path('login_user/', views.login_user, name='login_user'),
    path('register/', views.register, name='register'),
    path('save_user/', views.save_user, name='save_user'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.user_profile, name='profile'),
]

TabletopSimWeb/chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

TabletopSimWeb/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

TabletopSimWeb/accounts/views.py
from django.shortcuts import render, reverse, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

def register(request):
    message = request.GET.get('message', '')
    next = request.GET.get('next', '')
    context = {
        'next': next,
        'message': message
    }
    return render(request, 'accounts/register.html', context)

def save_user(request):
    if 'user_id' not in request.POST:
        next = request.GET.get('next', '')
        try:
            username = request.POST['username']
            email = request.POST['email']
            password = request.POST['password']
            password2 = request.POST['pass_check']
        except KeyError:
            return redirect(reverse('accounts:register') + '?message=invalid')
        if 150 < len(username) or len(username) < 6 or password != password2:
            return redirect(reverse('accounts:register') + '?message=invalid')


        if User.objects.filter(username=username):
            return redirect(reverse('accounts:register') + '?message=user_exists')
        user = User.objects.create_user(username, email, password)
        login(request, user)
        if next != '':
            return redirect(next)
        return redirect(reverse('tabletops:index'))
    else:
        pass

def login_page(request):
    message = request.GET.get('message', '')
    next = request.GET.get('next', '')
    context = {
        'next': next,
        'message': message
    }
    return render(request, 'accounts/login.html', context)

def login_user(request):
    try:
        next = request.POST['next']
        username = request.POST['username']
        password = request.POST['password']
    except KeyError:
        return redirect(reverse('accounts:login') + '?message=failure')
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        if next != '':
            return redirect(next)
        return redirect(reverse('tabletops:index'))
    if next == '':
        return redirect(reverse('accounts:login') + '?message=failure')
    return redirect(reverse('accounts:login') + '?message=failure&next='+next)

def logout_user(request):
    logout(request)
    return redirect(reverse('accounts:login') + '?message=loggedout')

@login_required
def user_home(request):
    return render(request, 'accounts/home.html')

@login_required
def user_profile(request):
    return render(request, 'accounts/user_profile.html')

TabletopSimWeb/accounts/templates/accounts/home.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome {{user.username}}</h1>
    <a href="{% url 'accounts:profile' %}">profile</a><br>
    <a href="{% url 'accounts:logout' %}">logout</a>
  </body>
</html>

TabletopSimWeb/accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    {% if message == 'failure' %}
    <h3 style="color:red">That username and password do not match</h3>
    {% elif message == 'loggedout' %}
    <h3 style="color:blue">Successfully logged out</h3>
    {% endif %}
    <h1>Login</h1>
    <form action="{% url 'accounts:login_user' %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="next" value="{{next}}"/>
      <input type="text" name="username" value="" placeholder="username">
      <input type="password" name="password" value="" placeholder="password">
      <button type="submit">login</button>
    </form>
    <a href="{% url 'accounts:register' %}">register</a>
  </body>
</html>

TabletopSimWeb/accounts/templates/accounts/register.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>register</title>

    <style type="text/css">
      form{
        display: flex;
        flex-direction: column;
        width: 80%;
        margin: 0 auto;
      }
    </style>
  </head>
  <body>
    <h1>Register</h1>
    {% if message == 'invalid' %}
    <p>The form submitted does not match with expected parameters, if you changed the site on your end please stop, if you did not, please report this issue to our support email.</p>
    {% elif message == 'user_exists' %}
    <p>This user already exists.</p>
    {% endif %}
    <form action="{% url 'accounts:save_user' %}{% if next %}next={{next}}{% endif %}" method="post">
      {% csrf_token %}
      <input id="userIn" type="text" name="username" value="" placeholder="username" required oninput="matchCheck()">
      <input type="email" name="email" value="" placeholder="email">
      <input id="password1" type="password" name="password" value="" placeholder="password" required oninput="matchCheck()">
      <input id="password2" type="password" name="pass_check" value="" placeholder="password check" required oninput="matchCheck()">
      <span id="noMatch"></span>
      <span id="bugcheck"></span>
      <button id="submitBtn" type="submit">register</button>
    </form>
    <a href="{% url 'accounts:login' %}">login</a>
    <script type="text/javascript">
      function matchCheck() {
        var password1 = document.getElementById('password1').value;
        var password2 = document.getElementById('password2').value;
        if (password2 == '') {
          passLenCheck();
        } else if (password1 != password2) {
          document.getElementById("submitBtn").disabled = true;
          document.getElementById('password2').style.border = 'red';
          document.getElementById("noMatch").innerHTML = '<p style="color:red">Passwords do not match</p>';
        } else {
          document.getElementById("noMatch").innerHTML = '';
          document.getElementById('password2').style.border = '1px solid lightgrey';
          passLenCheck();
        }
      }
      function passLenCheck() {
        var password= document.getElementById('password1').value;
        var len = password.length;
        var minlen = 8
        var badpass= 'password'
        var badpass2 = 'password123'
        if (password== '') {
          userLenCheck();
        } else if (len < minlen) {
          document.getElementById("submitBtn").disabled = true;
          document.getElementById('password1').style.border = 'red';
          document.getElementById("noMatch").innerHTML = '<p style="color:red">Password not long enough</p>';
        } else if (password== badpass) {
          document.getElementById("submitBtn").disabled = true;
          document.getElementById("noMatch").innerHTML = '<p style="color:red">Really?</p>';
          document.getElementById('password1').style.border = 'red';
        } else {
          document.getElementById("noMatch").innerHTML = '';
          document.getElementById('password1').style.border = '1px solid lightgrey';
          userLenCheck();
        }
      }
      function userLenCheck() {
        document.getElementById("noMatch").innerHTML = '<p style="color:red">ran ulenchk</p>';
        var user = document.getElementById('userIn').value;
        var len = user.length;
        if (len < 6) {
          document.getElementById("submitBtn").disabled = true;
          document.getElementById("noMatch").innerHTML = '<p style="color:red">Username not long enough</p>';
        } else {
          document.getElementById("noMatch").innerHTML = '';
          document.getElementById("submitBtn").disabled = false;
        }
      }

    </script>
  </body>
</html>

TabletopSimWeb/accounts/templates/accounts/user_profile.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    {{user.username}}<br>{{user.email}}
    <a href="{% url 'accounts:logout' %}">logout</a>
  </body>
</html>