TabletopSimWeb/TabletopSimWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('chat/', include('chat.urls')),
    path('games/', include('tabletops.urls')),
    path('admin/', admin.site.urls),
]

TabletopSimWeb/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('home/', views.user_home, name='home'),
    path('login/', views.login_page, name='login'),
    path('login_user/', views.login_user, name='login_user'),
    path('register/', views.register, name='register'),
    path('save_user/', views.save_user, name='save_user'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.user_profile, name='profile'),
]

TabletopSimWeb/chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

TabletopSimWeb/tabletops/urls.py
from django.urls import path

from . import views

app_name = 'tabletops'
urlpatterns = [
    path('', views.index, name='index'),
    path('templateadmin/', views.template_admin, name='template_admin'),
    path('template/<str:template_name>/', views.template_edit, name='template_edit'),
    path('createTemplate/', views.create, name='create'),
    path('newRoom/', views.create_room, name='newroom'),
    path('room/<str:room_name>/', views.room, name='room'),
    path('savetemp/', views.save_template, name='save_temp'),
    path('whitelist/', views.whitelist, name='whitelist'),
    path('history/', views.history, name='history'),
]

TabletopSimWeb/tabletops/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class BoardTemplate(models.Model):
    name = models.CharField(max_length=200, primary_key=True)
    board_state = models.TextField()
    board_width = models.IntegerField()
    board_height = models.IntegerField()
    visible = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class GameRoom(models.Model):
    name = models.SlugField(max_length=200, primary_key=True)
    public_spectators = models.BooleanField(default=False)
    admin = models.ForeignKey(User, on_delete=models.CASCADE, related_name='admingames')
    whitelist = models.ManyToManyField(User, related_name='gamerooms')
    board_state = models.TextField()
    off_board = models.TextField(default='[]')
    board_width = models.IntegerField()
    board_height = models.IntegerField()
    base_template = models.ForeignKey(BoardTemplate, on_delete=models.SET_NULL, related_name='gameInstances', null=True, blank=True)
    last_update = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name + ' - ' + self.admin.username


class Move(models.Model):
    room = models.ForeignKey(GameRoom, on_delete=models.CASCADE, related_name='moves')
    username = models.CharField(max_length=200)
    time = models.DateTimeField(default=timezone.now)
    content = models.TextField()

    def __str__(self):
        return self.username + ' - ' + self.time.strftime('%d %b %X')

class GameMessage(models.Model):
    room = models.ForeignKey(GameRoom, on_delete=models.CASCADE, related_name='GameMessages')
    username = models.CharField(max_length=200)
    time = models.DateTimeField(default=timezone.now)
    content = models.TextField()

    def __str__(self):
        return self.username + ' - ' + self.time.strftime('%d %b %X')

TabletopSimWeb/tabletops/views.py
from django.shortcuts import render, reverse, redirect, get_object_or_404
from .models import GameRoom, BoardTemplate, Move, GameMessage
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.models import User
from django.http import HttpResponse, JsonResponse
from django.core.validators import slug_re
import json

@login_required
def index(request):
    user = request.user
    admingames = user.admingames.order_by('last_update')
    gamerooms = user.gamerooms.order_by('last_update').exclude(admin=user)
    templates = BoardTemplate.objects.filter(visible=True)
    context = {
        'admingames': admingames, 'gamerooms': gamerooms, 'templates': templates
    }
    return render(request, 'tabletops/index.html', context)

@login_required
def create_room(request):
    parsed = json.loads(request.body)
    if not parsed['room_name']:
        return JsonResponse({'error': 'Please fill out room name'})
    if not slug_re.match(parsed['room_name']):
        return JsonResponse({'error': 'Please input a room name that is url safe(no spaces or special characters)'})
    if not parsed['template']:
        return JsonResponse({'error': 'Please pick a template'})
    room_name = parsed['room_name']
    if GameRoom.objects.filter(name=room_name).exists():
        return JsonResponse({'error': 'A room with that name already exists.'})
    template = BoardTemplate.objects.filter(name=parsed['template'])
    if template.exists():
        new = GameRoom(name=room_name, admin=request.user, base_template=template[0], board_state=template[0].board_state, board_width=template[0].board_width, board_height=template[0].board_height)
        new.save()
        new.whitelist.add(request.user)
        resp = {'redirect': reverse('tabletops:room', args=(new.name,))}
        return JsonResponse(resp)
    return JsonResponse({'error': 'Template with that name does not exist.'})

@login_required
def room(request, room_name):
    current_room = GameRoom.objects.filter(name=room_name)
    if current_room:
        if current_room[0].whitelist.filter(id=request.user.id).exists() or current_room[0].admin == request.user:
            return render(request, 'tabletops/board.html', {
            'room_name': current_room[0].name, 'board': current_room[0].board_state, 'board_width': current_room[0].board_width, 'board_height': current_room[0].board_height, 'calcVh': 97/current_room[0].board_height, 'off_board': current_room[0].off_board, 'admin': current_room[0].admin == request.user,
            })
    return redirect(reverse('tabletops:index'))

@staff_member_required
def template_admin(request):
    templates = BoardTemplate.objects.all()
    return render(request, 'tabletops/templateadmin.html', {
        'templates': templates
    })

@staff_member_required
def create(request):
    name = request.POST['name']
    height = int(request.POST['height'])
    width = int(request.POST['width'])
    board_state = '['
    for i in range(height*width):
        board_state += "{'color': 'white', 'pieces': [], 'x': " + str(i%width) + ", 'y': " + str((i//width) + 1) + "},"
    board_state += ']'
    new = BoardTemplate(name=name, board_state=board_state, board_width=width, board_height=height)
    new.save()
    return redirect(reverse('tabletops:template_edit', args=(new.name,)))

@staff_member_required
def template_edit(request, template_name):
    template = get_object_or_404(BoardTemplate, pk=template_name)
    return render(request, 'tabletops/template.html', {
        'board_state': template.board_state, 'board_width': template.board_width, 'board_height': template.board_height, 'template_name': template_name, 'visible': template.visible
    })

@staff_member_required
def save_template(request):
    parsed = json.loads(request.body)
    template = get_object_or_404(BoardTemplate, pk=parsed['template_name'])
    template.board_state = parsed['board_state']
    template.visible = parsed['visible']
    template.save()
    return HttpResponse('saved successfully')

@login_required
def history(request):
    data = json.loads(request.body)
    room = get_object_or_404(GameRoom, name=data['room_name'])
    whitelist = room.whitelist.all()
    if request.user in whitelist:
        history = []
        message_list = GameMessage.objects.all()
        for message in message_list:
            history.append(message)
        move_list = Move.objects.all()
        for move in move_list:
            history.append(move)
        history.sort(key=lambda moment: moment.time, reverse=True)
        hist_for_json = []
        for item in history:
            if item.__class__.__name__ == 'GameMessage':
                hist_for_json.append({'username': item.username, 'time': item.time.strftime('%d %b %Y %X %Z'), 'content': item.content})
            elif item.__class__.__name__ == 'Move':
                parsed = json.loads(item.content)
                if parsed['from']:
                    if 'pieceName' in parsed:
                        if parsed['from']['i'] == -1:
                            constructed_message = 'moved ' + parsed['pieceName'] + ' from off board to x: ' + str(parsed['to']['x']) + ', y: ' + str(parsed['to']['y']) + '.'
                        elif parsed['to']['i'] == -1:
                            constructed_message = 'moved ' + parsed['pieceName'] + ' from x: ' + str(parsed['from']['x']) + ', y: ' + str(parsed['from']['y']) + ' off of board.'
                        else:
                            constructed_message = 'moved ' + parsed['pieceName'] + ' from x: ' + str(parsed['from']['x']) + ', y: ' + str(parsed['from']['y']) + ' to x: ' + str(parsed['to']['x']) + ', y: ' + str(parsed['to']['y']) + '.'
                    else:
                        if parsed['from']['i'] == -1:
                            constructed_message = 'moved unknown piece from off board to x: ' + str(parsed['to']['x']) + ', y: ' + str(parsed['to']['y']) + '.'
                        elif parsed['to']['i'] == -1:
                            constructed_message = 'moved unknown piece from x: ' + str(parsed['from']['x']) + ', y: ' + str(parsed['from']['y']) + ' off of board.'
                        else:
                            constructed_message = 'moved unknown piece from x: ' + str(parsed['from']['x']) + ', y: ' + str(parsed['from']['y']) + ' to x: ' + str(parsed['to']['x']) + ', y: ' + str(parsed['to']['y']) + '.'
                hist_for_json.append({'username': 'system', 'time': item.time.strftime('%d %b %Y %X %Z'), 'content': item.username + constructed_message})
        return JsonResponse({'content': hist_for_json, 'error': ''})
    return JsonResponse({'content': [], 'error': "You ain't on the list"})

@login_required
def whitelist(request):
    data = json.loads(request.body)
    room = get_object_or_404(GameRoom, name=data['room_name'])
    whitelist = room.whitelist.all()
    username_list = []
    if request.user in whitelist:
        for user in whitelist:
            username_list.append(user.username)
    if request.user == room.admin:
        if data['action'] != 'invite':
            return JsonResponse({'whitelist': username_list, 'error': '', 'admin': True})
        found = User.objects.filter(username=data['username'])
        if found.exists():
            invitee = found[0]
            room.whitelist.add(invitee)
            username_list.append(invitee.username)
            return JsonResponse({'whitelist': username_list, 'error': '', 'admin': True})
        else:
            return JsonResponse({'whitelist': username_list, 'error': 'No user by that name found', 'admin': True})
    else:
        if data['action'] != 'invite':
            return JsonResponse({'whitelist': username_list, 'error': '', 'admin': False})
        else:
            return JsonResponse({'whitelist': username_list, 'error': 'non admins are not allowed to invite other players, nice try though', 'admin': False})

TabletopSimWeb/tabletops/templates/tabletops/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <title>{{user.username}}'s games</title>
    <style type="text/css">
      nav{
        background-color: lightgrey;
        display: flex;
        justify-content: flex-end;
        flex-direction: row;
      }
      nav span{
        margin-left: 0.5em;
      }
    </style>
  </head>
  <body>
    <nav>
      <span><a href="{% url 'accounts:home' %}">{{user.username}}</a></span><span><a href="{% url 'accounts:logout' %}">logout</a></span>
    </nav>
    <div>
      <h4>{{user.username}}'s games</h4>
      {% for game in admingames %}
        <a href="{% url 'tabletops:room' game.name %}">{{game.name}}</a><br>
      {% endfor %}
      <h4>Invited games</h4>
      {% for game in gamerooms %}
        <a href="{% url 'tabletops:room' game.name %}">{{game.admin.username}}: {{game.name}}</a><br>
      {% endfor %}
    </div>
    <div id="app">
      <div v-if="error">
        [[error]]
      </div>
      <input type="text" v-model="room_name" required>
      <select required v-model="template">
        {% for template in templates %}
          <option value="{{template.name}}">{{template.name}}</option>
        {% endfor %}
      </select>
      <button @click="newRoom">Create room</button>
    </div>
    <script type="text/javascript">
      let app = new Vue({
        el: '#app',
        delimiters: ['[[',']]'],
        data: {
          template: '',
          room_name: '',
          error: '',
        },
        methods: {
          newRoom: function() {
            if (this.template == '' || this.room_name == '') {
              this.error = 'please fully fill out the form'
              return null
            }
            axios({
              method: 'post',
              url: '{%url 'tabletops:newroom' %}',
              headers: {
                'X-CSRFToken': '{{csrf_token}}'
              },
              data: {
                'template': this.template,
                'room_name': this.room_name,
              }
            }).then(response => {
              console.log(response.data)
              if (response.data.error) {
                this.error = response.data.error
              } else if (response.data.redirect) {
                window.location.href = response.data.redirect
              }
            })
          }
        },
      })
    </script>
  </body>
</html>

TabletopSimWeb/tabletops/templates/tabletops/template.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <title>{{template_name}} template</title>
    <style type="text/css">
      .board{
        display: grid;
        grid-template-columns: repeat({{board_width}}, 150px);
        grid-template-rows: repeat({{board_height}}, 150px);
        width: 80%;
      }
      .chat{
        width: 20%;
        display: flex;
        flex-direction: column;
      }
      #app{
        display: flex;
        flex-direction: row;
      }
      .chatLog{
        display: flex;
        flex-direction: column;
        justify-content: flex-end;
      }
      .black{
        background-color: dimgrey;
      }
      .white{
        background-color: white;
      }
      .red{
        background-color: darkred;
      }
      .inlineTextIn {
        display: inline;
        width: 50px;
      }
    </style>
  </head>
  <body>
    <div id="app">
      <div class="board">
        <div v-for="spot in board" :class="spot.color" :title="'X: ' + spot.x + ', Y: '+spot.y+ ', pieces: '+ spot.pieces.length" @click="paintTool(spot)">
          <button @click="addPiece(spot)">place piece</button>
          <div v-if="spot.pieces.length != 0">
            <input type="text" v-model="spot.pieces[0].name">
            <input v-if="spot.pieces[0].name" type="url" v-model="spot.pieces[0].img">
            <button @click="removePiece(spot)">removePiece</button>
          </div>
          <button @click="paintSpot(spot)">paint</button>
        </div>
      </div>
      <div class="chat">
        <div>
          <input type="text" v-model="newPeiceName" placeholder="new peice name">
          <input type="url" v-model="newPeiceImg" placeholder="new peice img url">
        </div>
        <div>
          <p v-if="XYError">[[XYError]]</p>
          X = <input class="inlineTextIn" type="text" v-model="selectedXVal"> to <input class="inlineTextIn" type="text" v-model="modXVal"><button @click="changeXValues">change X</button><br>
          Y = <input class="inlineTextIn" type="text" v-model="selectedYVal"> to <input class="inlineTextIn" type="text" v-model="modYVal"><button @click="changeYValues">change Y</button><br>
        </div>
        <div>
          paint tool type:
          <select v-model="paint_tool">
            <option value="none">none</option>
            <option value="color">color</option>
            <option value="piece">add piece</option>
          </select>
        </div>
        <div>
          paint color
          <select v-model="paint_color">
            <option value="white">white</option>
            <option value="red">red</option>
            <option value="black">black</option>
          </select>
        </div>
        <div v-if="saveMessage">
          [[saveMessage]]
        </div>
        <input type="checkbox" id="visible" v-model="visible"><label for="visible">make visible</label>
        <button @click="saveBoard">save</button>
      </div>
    </div>
    <script type="text/javascript">
      let app = new Vue({
        el: '#app',
        delimiters: ['[[',']]'],
        data: {
          board: {{board_state|safe}},
          columns: {{board_width}},
          rows: {{board_height}},
          saveMessage: '',
          newPeiceName: '',
          newPeiceImg: '',
          selectedXVal: '',
          modXVal: '',
          selectedYVal: '',
          modYVal: '',
          visible: {% if visible %}true{% else %}false{% endif %},
          XYError: '',
          paint_color: 'white',
          paint_tool: 'none',
        },
        methods: {
          saveBoard: function() {
            axios({
              method: 'post',
              url: '{% url 'tabletops:save_temp' %}',
              headers: {
                'X-CSRFToken': '{{csrf_token}}'
              },
              data: {
                'board_state': JSON.stringify(this.board),
                'template_name': '{{template_name}}',
                'visible': this.visible,
              }
            }).then(response => {
              if (response.data){
                this.saveMessage = response.data
              }
            })
          },
          addPiece: function(spot) {
            spot.pieces.unshift({'name': this.newPeiceName, 'img': this.newPeiceImg})
          },
          removePiece: function(spot) {
            spot.pieces.shift()
          },
          changeXValues: function() {
            this.XYError = ''
            this.board.forEach((spot, i) => {
              if (spot.x == this.modXVal) {
                this.XYError = 'column exists with that value already, please use a placeholder if you wish to swap them'
              }
            })
            if (this.XYError == ''){
              this.board.forEach((spot, i) => {
                if (spot.x == this.selectedXVal) {
                  spot.x = this.modXVal
                }
              })
            }
          },
          changeYValues: function() {
            this.XYError = ''
            this.board.forEach((spot, i) => {
              if (spot.y == this.modYVal) {
                this.XYError = 'row exists with that value already, please use a placeholder if you wish to swap them'
              }
            })
            if (this.XYError == ''){
              this.board.forEach((spot, i) => {
                if (spot.y == this.selectedYVal) {
                  spot.y = this.modYVal
                }
              })
            }
          },
          paintSpot: function(spot) {
            spot.color = this.paint_color
          },
          paintTool: function(spot) {
            if (this.paint_tool == 'color') {
              this.paintSpot(spot)
            } else if (this.paint_tool == 'piece') {
              this.addPiece(spot)
            }
          }
        },
        created: function() {
          console.log(this.board);
        }
      })
    </script>
  </body>
</html>

TabletopSimWeb/tabletops/templates/tabletops/templateadmin.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <form class="" action="{% url 'tabletops:create' %}" method="post">
      {% csrf_token %}
      <input type="text" name="name" required><input type="number" name="height" value="8" required><input type="number" name="width" value="8" required><button type="submit">New template</button>
    </form>

      {% for template in templates %}
      <a href="{% url 'tabletops:template_edit' template.name %}">{{template.name}}</a>
      {% endfor %}
  </body>
</html>